package generator

import (
	"os"
	"path/filepath"
	"text/template"
)

type goTemplateData struct {
	GenerationModel
}

func (g *Generator) writeGoClient(outDir string, model GenerationModel) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}
	data := goTemplateData{GenerationModel: model}
	tmpl := template.Must(template.New("generated.go").Parse(goClientTemplate))
	file, err := os.Create(filepath.Join(outDir, "generated.go"))
	if err != nil {
		return err
	}
	defer file.Close()
	return tmpl.Execute(file, data)
}

func (g *Generator) writeGoMod(outDir string, model GenerationModel) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}
	tmpl := template.Must(template.New("go.mod").Parse(goModTemplate))
	file, err := os.Create(filepath.Join(outDir, "go.mod"))
	if err != nil {
		return err
	}
	defer file.Close()
	return tmpl.Execute(file, model)
}

// ── templates ──────────────────────────────────────────────────────────

const goClientTemplate = `// Code generated by github.com/fred29910/gowasm/cmd/generator. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	"strconv"

	runtime "{{.RuntimeImport}}"
)

{{range .Schemas}}
// {{.GoName}} ...
type {{.GoName}} struct {
{{range .Properties}}	{{.GoName}} {{.GoType}} ` + "`json:\"{{.Name}},omitempty\"`" + `
{{end}}}
{{end}}

{{range .Operations}}
// {{.RequestInterface}} ...
type {{.RequestInterface}} struct {
{{range .PathParams}}	{{.GoName}} {{.GoType}} ` + "`json:\"{{.Name}}\"`" + `
{{end}}{{range .QueryParams}}	{{.GoName}} {{.GoType}} ` + "`json:\"{{.Name}},omitempty\"`" + `
{{end}}	PathParams map[string]string ` + "`json:\"pathParams,omitempty\"`" + `
	Query      map[string]string ` + "`json:\"query,omitempty\"`" + `
	Headers    map[string]string ` + "`json:\"headers,omitempty\"`" + `
{{if .HasBody}}	Body       {{.BodyType}} ` + "`json:\"body,omitempty\"`" + `
{{end}}}

// ToRequest converts {{.RequestInterface}} to runtime.Request.
func {{.RequestInterface}}ToRequest(params {{.RequestInterface}}) runtime.Request {
	pathParams := make(map[string]string)
{{range .PathParams}}	pathParams["{{.Name}}"] = {{.GoType}}ToString(params.{{.GoName}})
{{end}}	return runtime.Request{
		Method:     "{{.Method}}",
		Path:       "{{.Path}}",
		PathParams: pathParams,
		Query:      copyStringMap(params.Query),
		Headers:    copyStringMap(params.Headers),
{{if .HasBody}}		Body:       params.Body,
{{else}}		Body:       nil,
{{end}}	}
}

// Call executes the {{.ID}} operation.
func {{.RequestInterface}}Call(ctx context.Context, params {{.RequestInterface}}) (*runtime.Response, error) {
	req := {{.RequestInterface}}ToRequest(params)
	return runtime.DefaultClient.Call(ctx, &req)
}
{{end}}

{{if .Operations}}
func init() {
{{range .Operations}}	runtime.RegisterOperation("{{.ID}}", func(ctx context.Context, req runtime.Request) (*runtime.Response, error) {
		return runtime.DefaultClient.Call(ctx, &req)
	})
{{end}}
}
{{end}}

func copyStringMap(in map[string]string) map[string]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func intToString(v int) string    { return strconv.Itoa(v) }
func int64ToString(v int64) string { return strconv.FormatInt(v, 10) }
func floatToString(v float64) string { return strconv.FormatFloat(v, 'f', -1, 64) }
func boolToString(v bool) string   { return strconv.FormatBool(v) }
`

const goModTemplate = `module {{.OutputModule}}

go 1.25.1

require github.com/fred29910/gowasm v0.0.0

replace github.com/fred29910/gowasm => {{.RuntimePath}}
`
