package generator

import (
	"os"
	"path/filepath"
	"text/template"
)

type tsTemplateData struct {
	GenerationModel
}

func (g *Generator) writeTSClient(outDir string, model GenerationModel) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	data := tsTemplateData{
		GenerationModel: model,
	}

	tmpl := template.Must(template.New("sdk.ts").Parse(tsClientTemplate))

	file, err := os.Create(filepath.Join(outDir, "sdk.ts"))
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}

func (g *Generator) writeDemoHTML(outDir string, model GenerationModel) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	tmpl := template.Must(template.New("index.html").Parse(demoHTMLTemplate))

	file, err := os.Create(filepath.Join(outDir, "index.html"))
	if err != nil {
		return err
	}
	defer file.Close()

	return tmpl.Execute(file, data)
}

// Placeholder - will be used in template execution
var data = tsTemplateData{}

const tsClientTemplate = `// Code generated by github.com/fred29910/gowasm/cmd/generator. DO NOT EDIT.

export interface WASMError {
	code: string;
	message: string;
	details?: string;
}

export interface HTTPResponse {
	status: number;
	headers: Record<string, string>;
	body: any;
	error?: WASMError;
}

export interface HTTPRequest {
	method: string;
	path: string;
	pathParams?: Record<string, string>;
	headers?: Record<string, string>;
	query?: Record<string, string>;
	body?: any;
}

{{range .Schemas}}
export interface {{.GoName}} {
{{range .Properties}}	{{.TSName}}{{if not .Required}}?{{end}}: {{.TSType}};
{{end}}
}
{{end}}

{{range .Operations}}
export interface {{.RequestInterface}} {
{{range .PathParams}}	{{.TSName}}{{if not .Required}}?{{end}}: {{.TSType}};
{{end}}{{range .QueryParams}}	{{.TSName}}{{if not .Required}}?{{end}}: {{.TSType}};
{{end}}	pathParams?: Record<string, string>;
	query?: Record<string, string>;
	headers?: Record<string, string>;
{{if .HasBody}}	body?: {{.BodyType}};
{{end}}
}
{{end}}

export interface WASMConfig {
	baseUrl: string;
	timeout?: number;
	headers?: Record<string, string>;
	credentials?: RequestCredentials;
}

export interface WASMReady {
	wasmReady: boolean;
}

declare global {
	interface Window {
		wasmReady?: boolean;
		wasmInitClient?: (config: WASMConfig) => Promise<any>;
		wasmCallAPI?: (operationId: string, request: HTTPRequest) => Promise<HTTPResponse>;
		wasmSetAuthToken?: (token: string, scheme?: string) => any;
		wasmClearAuthToken?: () => any;
		wasmGetConfig?: () => any;
	}
}

export class WASMSDK {
	private wasmUrl: string;
	private initialized: boolean = false;

	constructor(wasmUrl?: string) {
		this.wasmUrl = wasmUrl || './main.wasm';
	}

	async load(): Promise<void> {
		if (typeof window === 'undefined') {
			throw new Error('WASM SDK can only be used in browser environment');
		}

		const response = await fetch(this.wasmUrl);
		const bytes = await response.arrayBuffer();
		const wasmModule = await WebAssembly.instantiate(bytes, {
			env: {
				// Go WASM imports
			}
		});

		// Make exports available
		const { instance } = wasmModule;
		if (instance && instance.exports) {
			for (const [key, value] of Object.entries(instance.exports)) {
				(window as any)[key] = value;
			}
		}
	}

	async init(config: WASMConfig): Promise<void> {
		if (typeof window.wasmInitClient !== 'function') {
			throw new Error('WASM module not loaded. Call load() first.');
		}
		await window.wasmInitClient(config);
		this.initialized = true;
	}

	isInitialized(): boolean {
		return this.initialized;
	}

	setAuthToken(token: string, scheme: string = 'Bearer'): void {
		if (typeof window.wasmSetAuthToken !== 'function') {
			throw new Error('WASM module not loaded. Call load() first.');
		}
		window.wasmSetAuthToken(token, scheme);
	}

	clearAuthToken(): void {
		if (typeof window.wasmClearAuthToken !== 'function') {
			throw new Error('WASM module not loaded. Call load() first.');
		}
		window.wasmClearAuthToken();
	}

	async getConfig(): Promise<WASMConfig | null> {
		if (typeof window.wasmGetConfig !== 'function') {
			throw new Error('WASM module not loaded. Call load() first.');
		}
		const result = window.wasmGetConfig();
		return result.success ? result.config : null;
	}

	async callAPI(operationId: string, request: HTTPRequest): Promise<HTTPResponse> {
		if (typeof window.wasmCallAPI !== 'function') {
			throw new Error('WASM module not loaded. Call load() first.');
		}
		return window.wasmCallAPI(operationId, request);
	}
}

// Typed API methods
{{range .Operations}}
export async function {{.TSName}}(params: {{.RequestInterface}}): Promise<HTTPResponse> {
	const request: HTTPRequest = {
		method: '{{.Method}}',
		path: '{{.Path}}',
{{range .PathParams}}		pathParams: { '{{.Name}}': params.{{.TSName}} },
{{end}}		headers: params.headers || {},
		query: params.query || {},
{{if .HasBody}}		body: params.body,
{{end}}	};
	return (window as any).wasmCallAPI('{{.ID}}', request);
}
{{end}}
`

const demoHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>WASM SDK Demo - {{.InfoTitle}}</title>
	<script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 min-h-screen p-8">
	<div class="max-w-4xl mx-auto">
		<h1 class="text-3xl font-bold mb-4">{{.InfoTitle}} WASM SDK Demo</h1>
		<p class="text-gray-600 mb-6">Version: {{.InfoVersion}}</p>
		
		<div class="bg-white rounded-lg shadow p-6 mb-6">
			<h2 class="text-xl font-semibold mb-4">Configuration</h2>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium mb-1">Base URL</label>
					<input type="text" id="baseUrl" value="{{.BaseURL}}" class="w-full px-3 py-2 border rounded">
				</div>
				<button id="initBtn" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Initialize</button>
				<button id="loadBtn" class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 ml-2">Load WASM</button>
			</div>
		</div>

		<div class="bg-white rounded-lg shadow p-6">
			<h2 class="text-xl font-semibold mb-4">API Operations</h2>
			<div id="operations" class="space-y-4">
{{range .Operations}}
				<div class="border rounded p-4">
					<h3 class="font-medium">{{.ID}}</h3>
					<p class="text-sm text-gray-600 mb-2">{{.Method}} {{.Path}}</p>
					<button onclick="call{{.ID}}()" class="bg-purple-500 text-white px-3 py-1 rounded text-sm hover:bg-purple-600">Execute</button>
				</div>
{{end}}
			</div>
		</div>
	</div>

	<script type="module">
		import { WASMSDK } from './sdk.js';
		
		const sdk = new WASMSDK();
		
		document.getElementById('loadBtn').addEventListener('click', async () => {
			await sdk.load();
			console.log('WASM loaded');
		});
		
		document.getElementById('initBtn').addEventListener('click', async () => {
			await sdk.init({ baseUrl: document.getElementById('baseUrl').value });
			console.log('Client initialized');
		});

{{range .Operations}}
		window.call{{.ID}} = async () => {
			const response = await sdk.callAPI('{{.ID}}', {
				method: '{{.Method}}',
				path: '{{.Path}}'
			});
			console.log('{{.ID}} response:', response);
		};
{{end}}
	</script>
</body>
</html>
`